# -*- coding: utf-8 -*-
"""Bao_cao.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13LOubRJzA0pdqxMhZHSMS9ArcHS18rLX
"""

!pip install opencv-python-headless matplotlib
!pip install flask

cd /content/drive/MyDrive/Colab Notebooks/bao_cao

from google.colab.output import eval_js
print(eval_js("google.colab.kernel.proxyPort(5000)"))

from flask import Flask, render_template, request
import cv2
import numpy as np
import base64

app = Flask(__name__)

@app.route('/', methods=['GET', 'POST'])
def upload_file():
    if request.method == 'POST':
        file = request.files['file']
        img = cv2.imdecode(np.frombuffer(file.read(), np.uint8), cv2.IMREAD_UNCHANGED)
        if len(img.shape) == 3:
            img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        equ = cv2.equalizeHist(img)
        _, buffer = cv2.imencode('.jpg', equ)
        img_str = base64.b64encode(buffer).decode()
        return render_template('index.html', img_data=img_str)
    return render_template('index.html')

if __name__ == '__main__':
    app.run()